### ISSUE TITLE
Como contribuo?

### ISSUE THREAD

**Issue by Luccasoli** [jonataslaw/getx-community#1]
Fala @jonataslaw!

Estou fazendo um projeto pra estudo e estou usando o Getx, o que eu preciso fazer pra contribuir com esse repo?
link do projeto: https://github.com/Luccasoli/cinemapp

**Comment by jonataslaw** [comment]
Clica em "Fork". 
Adiciona tua pasta no teu fork. 
Clica em pull request. 
Eu vou receber a solicitação e dar merge. 

Em seguida eu adiciono no readme os créditos do projeto, e o teu git.

**Comment by Luccasoli** [comment]
Enviei, mas tu não acha que seria melhor apenas linkar os repositórios no Readme?
Nesse estilo https://github.com/Solido/awesome-flutter

**Comment by jonataslaw** [comment]
Pode ser, mas nesse estilo eu não conseguiria alterar os repos. Mas a ideia é boa. Talvez eu faça isso e peça as alterações antes de dar merge, valeu pela dica

**Comment by jonataslaw** [comment]
Considerei tua opinião e achei melhor fazer assim mesmo, assim ajuda quem fez o projeto também com stars e etc. A visibilidade é maior. 
Obrigado
